#!/usr/bin/env python3
"""Regenerate _data/publications.yml from Google Scholar (via SerpApi).

This file is fully auto-generated: every run replaces its contents with
the current list of publications from the configured Scholar profile.
Do not hand-edit _data/publications.yml — edits will be overwritten.
"""
import os
import re
import sys
import urllib.parse
import urllib.request
import json

AUTHOR_ID = "AcTEViAAAAAJ"
DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "_data")
PUBLICATIONS_FILE = os.path.join(DATA_DIR, "publications.yml")
MENTORING_FILE = os.path.join(DATA_DIR, "mentoring.yml")
SERPAPI_URL = "https://serpapi.com/search.json"
PUBLICATIONS_HEADER = (
    "# Auto-generated from Google Scholar by "
    ".github/workflows/update-publications.yml\n"
    "# Do not hand-edit — changes will be overwritten on the next run.\n"
)
MENTORING_HEADER = (
    "# Auto-generated by .github/workflows/update-publications.yml\n"
    "# Derived from a private MENTEE_NAMES secret + Scholar data — no names\n"
    "# are ever written here, only the resulting counts.\n"
    "# Do not hand-edit — changes will be overwritten on the next run.\n"
)


def fetch_articles(api_key):
    articles = []
    start = 0
    while True:
        params = {
            "engine": "google_scholar_author",
            "author_id": AUTHOR_ID,
            "api_key": api_key,
            "sort": "pubdate",
            "start": start,
        }
        url = SERPAPI_URL + "?" + urllib.parse.urlencode(params)
        with urllib.request.urlopen(url) as resp:
            payload = json.load(resp)

        if "error" in payload:
            raise RuntimeError(f"SerpApi error: {payload['error']}")

        page = payload.get("articles", [])
        if not page:
            break
        articles.extend(page)

        # Author API paginates in pages of 20; stop once we run out or
        # after a generous safety cap.
        if len(page) < 20 or start >= 100:
            break
        start += 20

    return articles


def escape(value):
    return value.replace('"', '\\"')


def format_entry(article):
    title = escape(article.get("title", "").strip())
    authors = escape(article.get("authors", "").strip())
    venue = escape(article.get("publication", "").strip())
    year = str(article.get("year", "")).strip()
    url = article.get("link", "").strip()

    lines = [f'- title: "{title}"']
    lines.append(f'  authors: "{authors}"' if authors else "  authors:")
    lines.append(f'  date: "{year}"' if year else "  date:")
    lines.append(f'  venue: "{venue}"' if venue else "  venue:")
    lines.append(f'  url: "{url}"' if url else "  url:")
    return "\n".join(lines)


def sort_key(article):
    match = re.search(r"\d{4}", str(article.get("year", "")))
    return int(match.group()) if match else 0


def normalize(s):
    return re.sub(r"[.\s]+", " ", s).strip().lower()


def name_forms(full_name):
    parts = full_name.split()
    if len(parts) < 2:
        return set()
    first, last = parts[0], parts[-1]
    return {normalize(f"{first[0]} {last}"), normalize(f"{first} {last}")}


def load_mentee_names():
    raw = os.environ.get("MENTEE_NAMES", "")
    return [line.strip() for line in raw.splitlines() if line.strip()]


def compute_mentoring_stats(articles, mentee_names):
    mentee_forms = {name: name_forms(name) for name in mentee_names}

    mentee_authorships = 0
    first_author_mentee_papers = 0

    for article in articles:
        tokens = [t.strip() for t in article.get("authors", "").split(",") if t.strip()]
        if not tokens:
            continue

        for token in tokens:
            token_norm = normalize(token)
            if any(token_norm in forms for forms in mentee_forms.values()):
                mentee_authorships += 1

        first_norm = normalize(tokens[0])
        if any(first_norm in forms for forms in mentee_forms.values()):
            first_author_mentee_papers += 1

    return {
        "mentees": len(mentee_names),
        "mentee_authorships": mentee_authorships,
        "first_author_mentee_papers": first_author_mentee_papers,
    }


def write_mentoring_file(stats):
    lines = [f"{key}: {value}" for key, value in stats.items()]
    with open(MENTORING_FILE, "w", encoding="utf-8") as f:
        f.write(MENTORING_HEADER + "\n" + "\n".join(lines) + "\n")


def main():
    api_key = os.environ.get("SERPAPI_KEY")
    if not api_key:
        print("SERPAPI_KEY not set", file=sys.stderr)
        sys.exit(1)

    articles = fetch_articles(api_key)
    articles.sort(key=sort_key, reverse=True)

    body = "\n\n".join(format_entry(a) for a in articles)
    with open(PUBLICATIONS_FILE, "w", encoding="utf-8") as f:
        f.write(PUBLICATIONS_HEADER + "\n" + body + "\n")
    print(f"Wrote {len(articles)} publication(s).")

    mentee_names = load_mentee_names()
    if mentee_names:
        stats = compute_mentoring_stats(articles, mentee_names)
        write_mentoring_file(stats)
        print(f"Wrote mentoring stats: {stats}")
    else:
        print("MENTEE_NAMES not set or empty; skipping mentoring stats.")


if __name__ == "__main__":
    main()
